services:
  twingate-connector:
    image: twingate/connector:latest
    container_name: twingate-connector
    restart: unless-stopped
    env_file:
      - ../../../.env
    environment:
      TWINGATE_NETWORK: ${TWINGATE_NETWORK}
      TWINGATE_ACCESS_TOKEN: ${TWINGATE_ACCESS_TOKEN}
      TWINGATE_REFRESH_TOKEN: ${TWINGATE_REFRESH_TOKEN}
      TWINGATE_LABEL_HOSTNAME: ${TWINGATE_LABEL_HOSTNAME:-homelab}
    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"
    networks:
      - shared
networks:
  shared:
    external: true
    name: ${SHARED_NETWORK}
