services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    env_file:
      - ../../../.env
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - ${DATA_ROOT}/redis:/data
    # ports:
    #   - "${REDIS_PORT:-6379}:6379"
    networks:
      - shared
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  shared:
    external: true
    name: ${SHARED_NETWORK}
